export const biglietti = [
    {
        title:'Kid Ygugi + Niky Savage',
        date:'27 lug 2024',
        when: 'sab 22:30',
        where:'SENIGALLIA',
        des:'Mamamia',
        dataCompleta: 'sabato, 27/07/2024 | 22:30',
        id: 11,
        imgBg: 'kid-yugi-niky-savage-biglietti.jpg',
        amount: 1,
        prezzoFalso: '€28,75',
        prezzoVero: 28.75,
        indirizzo: 'Via Giambattista Fiorini, 23, 60019 SENIGALLIA',
        imgIndirizzo: 'mamamia_biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'

    },
    {
        title:'KID YUGI',
        date:'13 lug 2024',
        when: 'sab 22:30',
        where:'MONOPOLI ',
        des:'Lido Baia del Sole',
        dataCompleta: 'sabato, 13/07/2024 | 22:30',
        id: 12,
        imgBg: '64-bars.jpg',
        amount: 1,
        prezzoFalso: '€22,00',
        prezzoVero: 22.00,
        indirizzo: 'C.da Pantanelli n.c, 70043 MONOPOLI BA ',
        imgIndirizzo: 'parco-pace-servigliano-biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
    {
        title:'KID YUGI',
        date:'11 ago 2024',
        when: 'dom 21:30',
        where:'PORDENONE',
        des:'Parco San Valentino',
        dataCompleta: 'domenica, 11/08/2024 | 21:30',
        id: 13,
        imgBg: 'BANNER2-960x365.png',
        classImgBg: 'transform scale-x-[-1]',
        amount: 1,
        prezzoFalso: '€34,50',
        prezzoVero: 34.50,
        indirizzo: 'Via S. Valentino, 33170 PORDENONE PN',
        imgIndirizzo: 'piazza-napoleone-biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
    {
        title:'KID YUGI + ARTIE 5IVE',
        date:'13 ago 2024',
        when: 'mar 21:30',
        where:'FOLLONICA',
        des:'Parco centrale',
        dataCompleta: 'martedì, 13/08/2024 | 21:30',
        id: 14,
        imgBg: 'kid-yugi-atie5ive-biglietti.jpg',
        amount: 1,
        prezzoFalso: '€34,50',
        prezzoVero: 34.50,
        indirizzo: 'via Massetana, 58022 FOLLONICA GR',
        imgIndirizzo: 'mamamia_biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
    {
        title:'Kid Ygugi + Salmo - Noyz',
        date:'12 lug 2024',
        when: 'ven 21:30',
        where:'CATANIA ',
        des:'Villa Bellini',
        dataCompleta: 'venerdì, 12/07/2024 | 21:30',
        id: 15,
        imgBg: 'salmo-noyz-biglietti.jpg',
        amount: 1,
        prezzoFalso: '€42,55',
        prezzoVero: 42.55,
        indirizzo: 'Via Etnea, 95123 CATANIA CT',
        imgIndirizzo: 'piazza-napoleone-biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'

    },
    {
        title:'KID YUGI',
        date:'18 lug 2024',
        when: 'gio 22:30',
        where:'PALERMO',
        des:'Cantieri Culturali alla Zisa',
        dataCompleta: 'giovedì, 18/07/2024 | 22:30',
        id: 16,
        imgBg: '64-bars.jpg',
        amount: 1,
        prezzoFalso: '€42,60',
        prezzoVero: 42.60,
        indirizzo: 'Via Paolo Gili, 90138 PALERMO PA',
        imgIndirizzo: 'mamamia_biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
    {
        title:'KID YUGI',
        date:'20 lug 2024',
        when: 'sab 21:30',
        where:'LUCCA',
        des:'Piazza Napoleone',
        dataCompleta: 'sabato, 20/07/2024 | 21:30',
        id: 17,
        imgBg: 'BANNER2-960x365.png',
        classImgBg: 'transform scale-x-[-1]',
        amount: 1,
        prezzoFalso: '€103,50',
        prezzoVero: 103.50,
        indirizzo: 'Piazza Napoleone, 55100 LUCCA',
        imgIndirizzo: 'piazza-napoleone-biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
    {
        title:'KID YUGI',
        date:'5 ago 2024',
        when: 'lun 21:30',
        where:'SERVIGLIANO',
        des:'Parco della Pace',
        dataCompleta: 'lunedì, 5/08/2024 | 21:30',
        id: 18,
        imgBg: 'BANNER2-960x365.png',
        classImgBg: 'transform scale-x-[-1]',
        amount: 1,
        prezzoFalso: '€42,55',
        prezzoVero: 42.55,
        indirizzo: 'Via Enrico Fermi, 63839 SERVIGLIANO (FM) FM',
        imgIndirizzo: 'parco-pace-servigliano-biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
    {
        title:'KID YUGI',
        date:'16 lug 2024',
        when: 'mar 22:30',
        where:'FRANCAVILLA AL MARE',
        des:'Lungomare Tosti',
        dataCompleta: 'martedì, 16/07/2024 | 22:30',
        id: 19,
        imgBg: 'BANNER2-960x365.png',
        classImgBg: 'transform scale-x-[-1]',
        amount: 1,
        prezzoFalso: '€28,75',
        prezzoVero: 28.75,
        indirizzo: 'Via Francesco Paolo Tosti, 66023 FRANCAVILLA AL MARE CH',
        imgIndirizzo: 'mamamia_biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'

    },
    {
        title:'KID YUGI',
        date:'30 lug 2024',
        when: 'mar 22:30',
        where:'CAPACCIO PAESTUM',
        des:'Planet Arena Templi di Paestum',
        dataCompleta: 'martedì, 30/07/2024 | 22:30',
        id: 20,
        imgBg: 'BANNER2-960x365.png',
        classImgBg: 'transform scale-x-[-1]',
        amount: 1,
        prezzoFalso: '€42,5',
        prezzoVero: 42.55,
        indirizzo: 'Via Magna Grecia, 84063 PAESTUM IT',
        imgIndirizzo: 'mamamia_biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
    {
        title:'KID YUGI',
        date:'11 ago 2024',
        when: 'dom 21:30',
        where:'PORDENONE',
        des:'Parco San Valentino',
        dataCompleta: 'domenica, 11/08/2024 | 21:30',
        id: 21,
        imgBg: 'BANNER2-960x365.png',
        classImgBg: 'transform scale-x-[-1]',
        amount: 1,
        prezzoFalso: '€34,50',
        prezzoVero: 34.50,
        indirizzo: 'Via S. Valentino, 33170 PORDENONE PN',
        imgIndirizzo: 'parco-pace-servigliano-biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
    {
        title:'KID YUGI',
        date:'15 ago 2024',
        when: 'gio 21:30',
        where:'GALLIPOLI',
        des:'Raffo Parco Gondar - Arena',
        dataCompleta: 'giovedì, 15/08/2024 | 21:30',
        id: 22,
        imgBg: 'BANNER2-960x365.png',
        classImgBg: 'transform scale-x-[-1]',
        amount: 1,
        prezzoFalso: '€34,50',
        prezzoVero: 34.50,
        indirizzo: 'Lungomare Galileo Galilei, 73014 GALLIPOLI ',
        imgIndirizzo: 'mamamia_biglietti.jpg',
        img_carrello: 'Biglietto_carrello.jpg'
    },
]