export const Merch = [
    {
        name: 'Felpa Grigia (I nomi del diavolo) KID YUGI',
        prezzo: '€ 24.99',
        prezzoCar: 24.99,
        filtro: 'Felpe',
        src: 'felpaBiancaAvanti.png',
        id: 1,
        amount: 1,
    },
    {
        name: 'Felpa Nera (I nomi del diavolo) KID YUGI',
        prezzo: '€ 24.99',
        prezzoCar: 24.99,
        filtro: 'Felpe',
        src: 'felpaNeraAvanti.png',
        id: 2,
        amount: 1,
    },
    {
        name: 'Maglietta Grigia (I nomi del diavolo) KID YUGI',
        prezzo: '€ 24.99',
        prezzoCar: 24.99,
        filtro: 'Magliette',
        src: 'magliettaGrigiaAvanti.png',
        id: 3,
        amount: 1,
    },
    {
        name: 'Maglietta Nera (I nomi del diavolo) KID YUGI',
        prezzo: '€ 24.99',
        prezzoCar: 24.99,
        filtro: 'Magliette',
        src: 'MagliettaNeraAvanti.png',
        id: 4,
        amount: 1,
    },
    {
        name: 'I NOMI DEL DIAVOLO',
        prezzo: '€ 25.90',
        des: '(Vinile Sangue Edition)',
        prezzoCar: 25.90,
        filtro: 'Music',
        src: 'iNomiDel-removebg-preview.png',
        id: 5,
        amount: 1,
    },
    {
        name: 'QUARTO DI BUE',
        des: '(Vinile Colorato)',
        prezzo: '€ 27.50',
        prezzoCar: 27.50,
        filtro: 'Music',
        src: 'quartoDiBue-removebg-preview.png',
        id: 6,
        amount: 1,
    },
    {
        name: 'I NOMI DEL DIAVOLO',
        des: '(CD)',
        prezzo: '€ 13.90',
        prezzoCar: 13.90,
        filtro: 'Music',
        src: 'CDKid.png',
        id: 7,
        amount: 1,
    },
    {
        name: 'I NOMI DEL DIAVOLO',
        des: '(Vinile Autografato Dark Edition Alternative Cover)',
        prezzo: '€ 25.90',
        prezzoCar: 25.90,
        filtro: 'Music',
        src: 'iNomiDelDIavoloDark.png',
        id: 8,
        amount: 1,
    },
    {
        name: 'I NOMI DEL DIAVOLO',
        des: '(Vinile Autografato Ombra Edition)',
        prezzo: '€ 25.90',
        prezzoCar: 25.90,
        filtro: 'Music',
        src: 'LP-Ombra.png',
        id: 9,
        amount: 1,
    },
    {
        name: 'Quarto Di Bue',
        des: '(Vinile edizione limitata)',
        prezzo: '€ 27.90',
        prezzoCar: 27.90,
        filtro: 'Music',
        src: 'QuartoDIBueLimitata.png',
        id: 10,
        amount: 1,
    },
    
]